#@ load("@ytt:data", "data")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tap-installer
  namespace: tap-installer
  labels:
    app.kubernetes.io/name: tap-installer
    app.kubernetes.io/part-of: tap-installer
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 3600
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tap-installer
        app.kubernetes.io/part-of: tap-installer
        app.kubernetes.io/component: job
    spec:
      restartPolicy: Never
      serviceAccount: tap-installer-sa
      containers:
      - name: installer
        image: #@ data.values.installer.image
        securityContext:
          runAsUser: 1000
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: tap-installer
        env:
        - name: TAP_INSTALLER_CONFIG
          value: /home/tap-installer/config/values.yaml
        volumeMounts:
          - name: config
            readOnly: true
            mountPath: /home/tap-installer/config/values.yaml
            subPath: values.yaml
      volumes:
      - name: config
        secret:
          secretName: tap-installer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tap-installer
  namespace: tap-installer
  annotations:
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/versioned-keep-original: ""
data:
  TAP_VERSION: 1.4.0
  TAP_INSTALLER_VERSION: 1.4.0-alpha.1
  TAP_INSTALLER_IMAGE: #@ data.values.installer.image
