apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-installer-sa
  namespace: tap-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tap-installer-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tap-installer-role-binding
subjects:
- kind: ServiceAccount
  name: tap-installer-sa
  namespace: tap-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tap-installer-role
